#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Format staged files with Prettier and add them to the commit
npx lint-staged

# Run linting
npm run lint || exit 1

# Run tests
npm test -- --bail || exit 1



